// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_lookup.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const lookupSessionByHash = `-- name: LookupSessionByHash :one
SELECT id, tenant_id, token_hash FROM app.sessions WHERE token_hash = $1
`

type LookupSessionByHashRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	TokenHash []byte
}

func (q *Queries) LookupSessionByHash(ctx context.Context, tokenHash []byte) (LookupSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, lookupSessionByHash, tokenHash)
	var i LookupSessionByHashRow
	err := row.Scan(&i.ID, &i.TenantID, &i.TokenHash)
	return i, err
}
