// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package store

import (
	"context"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM app.sessions
WHERE expires_at < now() - interval '30 days'
   OR revoked_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredUserTokens = `-- name: DeleteExpiredUserTokens :execrows
DELETE FROM app.user_tokens
WHERE expires_at < now() - interval '30 days'
  AND (purpose <> 'invitation' OR used_at IS NOT NULL OR revoked_at IS NOT NULL)
`

func (q *Queries) DeleteExpiredUserTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUserTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldLoginThrottles = `-- name: DeleteOldLoginThrottles :execrows
DELETE FROM app.login_throttles
WHERE last_failed_at < now() - interval '1 day'
  AND (locked_until IS NULL OR locked_until < now())
`

func (q *Queries) DeleteOldLoginThrottles(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldLoginThrottles)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
