// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLoginUser = `-- name: GetLoginUser :one
SELECT password_hash, status, role FROM app.users
WHERE tenant_id = $1 AND id = $2
`

type GetLoginUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type GetLoginUserRow struct {
	PasswordHash pgtype.Text
	Status       string
	Role         string
}

func (q *Queries) GetLoginUser(ctx context.Context, arg GetLoginUserParams) (GetLoginUserRow, error) {
	row := q.db.QueryRow(ctx, getLoginUser, arg.TenantID, arg.UserID)
	var i GetLoginUserRow
	err := row.Scan(&i.PasswordHash, &i.Status, &i.Role)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT s.id AS session_id, s.user_id, s.revoked_at, s.created_at, s.last_seen_at, s.expires_at,
       u.email, u.name, u.role, u.status, u.email_verified_at
FROM app.sessions AS s
JOIN app.users AS u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetSessionUserParams struct {
	TenantID  uuid.UUID
	SessionID uuid.UUID
}

type GetSessionUserRow struct {
	SessionID       uuid.UUID
	UserID          uuid.UUID
	RevokedAt       *time.Time
	CreatedAt       time.Time
	LastSeenAt      time.Time
	ExpiresAt       time.Time
	Email           string
	Name            pgtype.Text
	Role            string
	Status          string
	EmailVerifiedAt *time.Time
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, arg.TenantID, arg.SessionID)
	var i GetSessionUserRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getTokenFlowTenantName = `-- name: GetTokenFlowTenantName :one
SELECT name FROM app.tenants WHERE id = $1
`

func (q *Queries) GetTokenFlowTenantName(ctx context.Context, tenantID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTokenFlowTenantName, tenantID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getTokenFlowUser = `-- name: GetTokenFlowUser :one
SELECT email, status, role, email_verified_at FROM app.users
WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetTokenFlowUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type GetTokenFlowUserRow struct {
	Email           string
	Status          string
	Role            string
	EmailVerifiedAt *time.Time
}

func (q *Queries) GetTokenFlowUser(ctx context.Context, arg GetTokenFlowUserParams) (GetTokenFlowUserRow, error) {
	row := q.db.QueryRow(ctx, getTokenFlowUser, arg.TenantID, arg.UserID)
	var i GetTokenFlowUserRow
	err := row.Scan(
		&i.Email,
		&i.Status,
		&i.Role,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getTokenForUpdate = `-- name: GetTokenForUpdate :one
SELECT id, user_id, purpose, expires_at, used_at, revoked_at FROM app.user_tokens
WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetTokenForUpdateParams struct {
	TenantID uuid.UUID
	TokenID  uuid.UUID
}

type GetTokenForUpdateRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	ExpiresAt time.Time
	UsedAt    *time.Time
	RevokedAt *time.Time
}

func (q *Queries) GetTokenForUpdate(ctx context.Context, arg GetTokenForUpdateParams) (GetTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTokenForUpdate, arg.TenantID, arg.TokenID)
	var i GetTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenUser = `-- name: GetTokenUser :one
SELECT user_id FROM app.user_tokens WHERE tenant_id = $1 AND id = $2
`

type GetTokenUserParams struct {
	TenantID uuid.UUID
	TokenID  uuid.UUID
}

func (q *Queries) GetTokenUser(ctx context.Context, arg GetTokenUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTokenUser, arg.TenantID, arg.TokenID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email FROM app.users WHERE tenant_id = $1 AND id = $2
`

type GetUserEmailParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetUserEmail(ctx context.Context, arg GetUserEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmail, arg.TenantID, arg.UserID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const insertFirstAdmin = `-- name: InsertFirstAdmin :one
INSERT INTO app.users (tenant_id, email, name, password_hash, role, status)
VALUES ($1, $2, $3, $4, 'admin', 'active')
RETURNING id
`

type InsertFirstAdminParams struct {
	TenantID     uuid.UUID
	Email        string
	Name         pgtype.Text
	PasswordHash pgtype.Text
}

func (q *Queries) InsertFirstAdmin(ctx context.Context, arg InsertFirstAdminParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertFirstAdmin,
		arg.TenantID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO app.sessions (tenant_id, user_id, token_hash, created_at, last_seen_at, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertSessionParams struct {
	TenantID   uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Ip         *netip.Addr
	UserAgent  pgtype.Text
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUserToken = `-- name: InsertUserToken :exec
INSERT INTO app.user_tokens (tenant_id, user_id, purpose, token_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUserTokenParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertUserToken(ctx context.Context, arg InsertUserTokenParams) error {
	_, err := q.db.Exec(ctx, insertUserToken,
		arg.TenantID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertVerificationToken = `-- name: InsertVerificationToken :exec
INSERT INTO app.user_tokens (tenant_id, user_id, purpose, token_hash, created_at, expires_at)
VALUES ($1, $2, 'email_verification', $3, $4, $5)
`

type InsertVerificationTokenParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertVerificationToken,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE app.users SET email_verified_at = $1, updated_at = $1
WHERE tenant_id = $2 AND id = $3 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOpenUserTokens = `-- name: RevokeOpenUserTokens :exec
UPDATE app.user_tokens SET revoked_at = $1
WHERE tenant_id = $2 AND user_id = $3 AND purpose = $4
  AND used_at IS NULL AND revoked_at IS NULL
`

type RevokeOpenUserTokensParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
	Purpose  string
}

func (q *Queries) RevokeOpenUserTokens(ctx context.Context, arg RevokeOpenUserTokensParams) error {
	_, err := q.db.Exec(ctx, revokeOpenUserTokens,
		arg.Now,
		arg.TenantID,
		arg.UserID,
		arg.Purpose,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE app.sessions SET revoked_at = $1, revoked_reason = 'logout'
WHERE tenant_id = $2 AND id = $3 AND revoked_at IS NULL AND expires_at > $1 AND last_seen_at > $4
RETURNING user_id
`

type RevokeSessionParams struct {
	Now        *time.Time
	TenantID   uuid.UUID
	SessionID  uuid.UUID
	IdleCutoff time.Time
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeSession,
		arg.Now,
		arg.TenantID,
		arg.SessionID,
		arg.IdleCutoff,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE app.sessions SET revoked_at = $1, revoked_reason = 'password_reset'
WHERE tenant_id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, arg.Now, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setResetPassword = `-- name: SetResetPassword :exec
UPDATE app.users SET password_hash = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type SetResetPasswordParams struct {
	PasswordHash pgtype.Text
	Now          time.Time
	TenantID     uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) SetResetPassword(ctx context.Context, arg SetResetPasswordParams) error {
	_, err := q.db.Exec(ctx, setResetPassword,
		arg.PasswordHash,
		arg.Now,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE app.sessions SET last_seen_at = $1
WHERE tenant_id = $2 AND id = $3
`

type TouchSessionParams struct {
	LastSeenAt time.Time
	TenantID   uuid.UUID
	SessionID  uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.LastSeenAt, arg.TenantID, arg.SessionID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE app.users SET password_hash = $1, updated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdatePasswordHashParams struct {
	PasswordHash pgtype.Text
	Now          time.Time
	TenantID     uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash,
		arg.PasswordHash,
		arg.Now,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const useUserToken = `-- name: UseUserToken :execrows
UPDATE app.user_tokens SET used_at = $1
WHERE tenant_id = $2 AND id = $3 AND purpose = $4
  AND used_at IS NULL AND revoked_at IS NULL AND expires_at > $1
`

type UseUserTokenParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	TokenID  uuid.UUID
	Purpose  string
}

func (q *Queries) UseUserToken(ctx context.Context, arg UseUserTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, useUserToken,
		arg.Now,
		arg.TenantID,
		arg.TokenID,
		arg.Purpose,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
