// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionUser = `-- name: GetSessionUser :one
SELECT s.id AS session_id, s.user_id, s.revoked_at, s.created_at, s.last_seen_at, s.expires_at,
       u.email, u.name, u.role, u.status, u.email_verified_at
FROM app.sessions AS s
JOIN app.users AS u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetSessionUserParams struct {
	TenantID  uuid.UUID
	SessionID uuid.UUID
}

type GetSessionUserRow struct {
	SessionID       uuid.UUID
	UserID          uuid.UUID
	RevokedAt       *time.Time
	CreatedAt       time.Time
	LastSeenAt      time.Time
	ExpiresAt       time.Time
	Email           string
	Name            pgtype.Text
	Role            string
	Status          string
	EmailVerifiedAt *time.Time
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, arg.TenantID, arg.SessionID)
	var i GetSessionUserRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email FROM app.users WHERE tenant_id = $1 AND id = $2
`

type GetUserEmailParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetUserEmail(ctx context.Context, arg GetUserEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmail, arg.TenantID, arg.UserID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const insertFirstAdmin = `-- name: InsertFirstAdmin :one
INSERT INTO app.users (tenant_id, email, name, password_hash, role, status)
VALUES ($1, $2, $3, $4, 'admin', 'active')
RETURNING id
`

type InsertFirstAdminParams struct {
	TenantID     uuid.UUID
	Email        string
	Name         pgtype.Text
	PasswordHash pgtype.Text
}

func (q *Queries) InsertFirstAdmin(ctx context.Context, arg InsertFirstAdminParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertFirstAdmin,
		arg.TenantID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO app.sessions (tenant_id, user_id, token_hash, created_at, last_seen_at, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertSessionParams struct {
	TenantID   uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Ip         *netip.Addr
	UserAgent  pgtype.Text
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertVerificationToken = `-- name: InsertVerificationToken :exec
INSERT INTO app.user_tokens (tenant_id, user_id, purpose, token_hash, created_at, expires_at)
VALUES ($1, $2, 'email_verification', $3, $4, $5)
`

type InsertVerificationTokenParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertVerificationToken,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE app.sessions SET last_seen_at = $1
WHERE tenant_id = $2 AND id = $3
`

type TouchSessionParams struct {
	LastSeenAt time.Time
	TenantID   uuid.UUID
	SessionID  uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.LastSeenAt, arg.TenantID, arg.SessionID)
	return err
}
