// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateInvitedUser = `-- name: ActivateInvitedUser :exec
UPDATE app.users SET status = 'active', name = $1, password_hash = $2,
  email_verified_at = $3, status_changed_at = $3, updated_at = $3
WHERE tenant_id = $4 AND id = $5
`

type ActivateInvitedUserParams struct {
	Name         pgtype.Text
	PasswordHash pgtype.Text
	Now          *time.Time
	TenantID     uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) ActivateInvitedUser(ctx context.Context, arg ActivateInvitedUserParams) error {
	_, err := q.db.Exec(ctx, activateInvitedUser,
		arg.Name,
		arg.PasswordHash,
		arg.Now,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM app.users WHERE tenant_id = $1 AND status = 'active' AND role = 'admin'
`

func (q *Queries) CountActiveAdmins(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findInvitedEmail = `-- name: FindInvitedEmail :one
SELECT id, status FROM app.users WHERE tenant_id = $1 AND email = $2
`

type FindInvitedEmailParams struct {
	TenantID uuid.UUID
	Email    string
}

type FindInvitedEmailRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) FindInvitedEmail(ctx context.Context, arg FindInvitedEmailParams) (FindInvitedEmailRow, error) {
	row := q.db.QueryRow(ctx, findInvitedEmail, arg.TenantID, arg.Email)
	var i FindInvitedEmailRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getManagedUser = `-- name: GetManagedUser :one
SELECT u.id, u.email, u.name, u.role, u.status, u.email_verified_at, u.created_at,
       tok.expires_at AS invitation_expires_at
FROM app.users AS u
LEFT JOIN app.user_tokens AS tok ON tok.tenant_id = u.tenant_id AND tok.user_id = u.id
  AND u.status = 'invited' AND tok.purpose = 'invitation' AND tok.used_at IS NULL AND tok.revoked_at IS NULL
WHERE u.tenant_id = $1 AND u.id = $2
`

type GetManagedUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type GetManagedUserRow struct {
	ID                  uuid.UUID
	Email               string
	Name                pgtype.Text
	Role                string
	Status              string
	EmailVerifiedAt     *time.Time
	CreatedAt           time.Time
	InvitationExpiresAt *time.Time
}

func (q *Queries) GetManagedUser(ctx context.Context, arg GetManagedUserParams) (GetManagedUserRow, error) {
	row := q.db.QueryRow(ctx, getManagedUser, arg.TenantID, arg.UserID)
	var i GetManagedUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.InvitationExpiresAt,
	)
	return i, err
}

const insertInvitedUser = `-- name: InsertInvitedUser :one
INSERT INTO app.users (tenant_id, email, role, status, created_at, updated_at, status_changed_at)
VALUES ($1, $2, $3, 'invited', $4, $4, $4) RETURNING id
`

type InsertInvitedUserParams struct {
	TenantID uuid.UUID
	Email    string
	Role     string
	Now      time.Time
}

func (q *Queries) InsertInvitedUser(ctx context.Context, arg InsertInvitedUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertInvitedUser,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listManagedUsers = `-- name: ListManagedUsers :many
SELECT u.id, u.email, u.name, u.role, u.status, u.email_verified_at, u.created_at,
       tok.expires_at AS invitation_expires_at
FROM app.users AS u
LEFT JOIN app.user_tokens AS tok ON tok.tenant_id = u.tenant_id AND tok.user_id = u.id
  AND u.status = 'invited' AND tok.purpose = 'invitation' AND tok.used_at IS NULL AND tok.revoked_at IS NULL
WHERE u.tenant_id = $1 ORDER BY u.created_at, u.id
`

type ListManagedUsersRow struct {
	ID                  uuid.UUID
	Email               string
	Name                pgtype.Text
	Role                string
	Status              string
	EmailVerifiedAt     *time.Time
	CreatedAt           time.Time
	InvitationExpiresAt *time.Time
}

func (q *Queries) ListManagedUsers(ctx context.Context, tenantID uuid.UUID) ([]ListManagedUsersRow, error) {
	rows, err := q.db.Query(ctx, listManagedUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagedUsersRow
	for rows.Next() {
		var i ListManagedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.InvitationExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockManagedUser = `-- name: LockManagedUser :one
SELECT id, email, name, role, status, password_hash, email_verified_at, created_at
FROM app.users WHERE tenant_id = $1 AND id = $2 FOR NO KEY UPDATE
`

type LockManagedUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type LockManagedUserRow struct {
	ID              uuid.UUID
	Email           string
	Name            pgtype.Text
	Role            string
	Status          string
	PasswordHash    pgtype.Text
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
}

func (q *Queries) LockManagedUser(ctx context.Context, arg LockManagedUserParams) (LockManagedUserRow, error) {
	row := q.db.QueryRow(ctx, lockManagedUser, arg.TenantID, arg.UserID)
	var i LockManagedUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockUsersTenant = `-- name: LockUsersTenant :one
SELECT id FROM app.tenants WHERE id = $1 FOR NO KEY UPDATE
`

func (q *Queries) LockUsersTenant(ctx context.Context, tenantID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockUsersTenant, tenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeDisabledUserSessions = `-- name: RevokeDisabledUserSessions :execrows
UPDATE app.sessions SET revoked_at = $1, revoked_reason = 'user_disabled'
WHERE tenant_id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeDisabledUserSessionsParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeDisabledUserSessions(ctx context.Context, arg RevokeDisabledUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDisabledUserSessions, arg.Now, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDisabledUserTokens = `-- name: RevokeDisabledUserTokens :exec
UPDATE app.user_tokens SET revoked_at = $1
WHERE tenant_id = $2 AND user_id = $3 AND used_at IS NULL AND revoked_at IS NULL
`

type RevokeDisabledUserTokensParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeDisabledUserTokens(ctx context.Context, arg RevokeDisabledUserTokensParams) error {
	_, err := q.db.Exec(ctx, revokeDisabledUserTokens, arg.Now, arg.TenantID, arg.UserID)
	return err
}

const setManagedUserRole = `-- name: SetManagedUserRole :exec
UPDATE app.users SET updated_at = $1, role = $2 WHERE tenant_id = $3 AND id = $4
`

type SetManagedUserRoleParams struct {
	Now      time.Time
	Role     string
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) SetManagedUserRole(ctx context.Context, arg SetManagedUserRoleParams) error {
	_, err := q.db.Exec(ctx, setManagedUserRole,
		arg.Now,
		arg.Role,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const setManagedUserStatus = `-- name: SetManagedUserStatus :exec
UPDATE app.users SET status = $1, updated_at = $2, status_changed_at = $2
WHERE tenant_id = $3 AND id = $4
`

type SetManagedUserStatusParams struct {
	Status   string
	Now      time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) SetManagedUserStatus(ctx context.Context, arg SetManagedUserStatusParams) error {
	_, err := q.db.Exec(ctx, setManagedUserStatus,
		arg.Status,
		arg.Now,
		arg.TenantID,
		arg.UserID,
	)
	return err
}
