// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO app.audit_log (
    tenant_id, actor_user_id, action, target_type, target_id, data, ip, user_agent, request_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
`

type InsertAuditParams struct {
	TenantID    uuid.UUID
	ActorUserID uuid.NullUUID
	Action      string
	TargetType  pgtype.Text
	TargetID    uuid.NullUUID
	Data        []byte
	Ip          *netip.Addr
	UserAgent   pgtype.Text
	RequestID   pgtype.Text
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Data,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}
