// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const provisionTenantRole = `-- name: ProvisionTenantRole :one
SELECT provisioning.provision_tenant_role($1::uuid)
`

func (q *Queries) ProvisionTenantRole(ctx context.Context, tenantID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, provisionTenantRole, tenantID)
	var provision_tenant_role string
	err := row.Scan(&provision_tenant_role)
	return provision_tenant_role, err
}

const setSignupLockTimeout = `-- name: SetSignupLockTimeout :one
SELECT set_config('lock_timeout', $1::text, true)
`

func (q *Queries) SetSignupLockTimeout(ctx context.Context, timeout string) (string, error) {
	row := q.db.QueryRow(ctx, setSignupLockTimeout, timeout)
	var set_config string
	err := row.Scan(&set_config)
	return set_config, err
}
