// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countTenantRoles = `-- name: CountTenantRoles :one
SELECT count(*) FROM pg_catalog.pg_roles
WHERE rolname ~ '^crm_t_[0-9a-f]{32}$'
`

func (q *Queries) CountTenantRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenants = `-- name: CountTenants :one
SELECT count(*) FROM app.tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantsWithoutRole = `-- name: CountTenantsWithoutRole :one
SELECT count(*) FROM app.tenants t
WHERE NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_roles r
    WHERE r.rolname = 'crm_t_' || replace(t.id::text, '-', '')
)
`

func (q *Queries) CountTenantsWithoutRole(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantsWithoutRole)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listTenantIDs = `-- name: ListTenantIDs :many
SELECT id FROM app.tenants ORDER BY id
`

func (q *Queries) ListTenantIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTenantIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const provisionTenantRole = `-- name: ProvisionTenantRole :one
SELECT provisioning.provision_tenant_role($1::uuid)
`

func (q *Queries) ProvisionTenantRole(ctx context.Context, tenantID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, provisionTenantRole, tenantID)
	var provision_tenant_role string
	err := row.Scan(&provision_tenant_role)
	return provision_tenant_role, err
}

const setSignupLockTimeout = `-- name: SetSignupLockTimeout :one
SELECT set_config('lock_timeout', $1::text, true)
`

func (q *Queries) SetSignupLockTimeout(ctx context.Context, timeout string) (string, error) {
	row := q.db.QueryRow(ctx, setSignupLockTimeout, timeout)
	var set_config string
	err := row.Scan(&set_config)
	return set_config, err
}
