// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantSummary = `-- name: GetTenantSummary :one
SELECT id, name, base_currency, timezone, logo_object_key
FROM app.tenants WHERE id = $1
`

type GetTenantSummaryRow struct {
	ID            uuid.UUID
	Name          string
	BaseCurrency  string
	Timezone      string
	LogoObjectKey pgtype.Text
}

func (q *Queries) GetTenantSummary(ctx context.Context, tenantID uuid.UUID) (GetTenantSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTenantSummary, tenantID)
	var i GetTenantSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.Timezone,
		&i.LogoObjectKey,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO app.tenants (id, name, base_currency, timezone, industry_template_code, industry_template_version)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTenantParams struct {
	TenantID                uuid.UUID
	Name                    string
	BaseCurrency            string
	Timezone                string
	IndustryTemplateCode    string
	IndustryTemplateVersion int32
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.TenantID,
		arg.Name,
		arg.BaseCurrency,
		arg.Timezone,
		arg.IndustryTemplateCode,
		arg.IndustryTemplateVersion,
	)
	return err
}
