// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcspike

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AppSpikeItem struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Email      string
	SecretHash []byte
	Ip         *netip.Addr
	ParentID   uuid.NullUUID
	CreatedAt  time.Time
}
