// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcspike

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, base_currency, timezone, logo_object_key, created_at, updated_at
FROM app.tenants
WHERE id = $1
`

type GetTenantByIDRow struct {
	ID            uuid.UUID
	Name          string
	BaseCurrency  string
	Timezone      string
	LogoObjectKey pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetTenantByID(ctx context.Context, tenantID uuid.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.Timezone,
		&i.LogoObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO app.audit_log (tenant_id, actor_user_id, action, target_type, target_id, ip, user_agent, request_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id, occurred_at, ip
`

type InsertAuditLogParams struct {
	TenantID    uuid.UUID
	ActorUserID uuid.NullUUID
	Action      string
	TargetType  pgtype.Text
	TargetID    uuid.NullUUID
	Ip          *netip.Addr
	UserAgent   pgtype.Text
	RequestID   pgtype.Text
}

type InsertAuditLogRow struct {
	ID         uuid.UUID
	OccurredAt time.Time
	Ip         *netip.Addr
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
	)
	var i InsertAuditLogRow
	err := row.Scan(&i.ID, &i.OccurredAt, &i.Ip)
	return i, err
}

const lookupUserByEmail = `-- name: LookupUserByEmail :one
SELECT id, tenant_id FROM app.users WHERE email = $1
`

type LookupUserByEmailRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

// Phase 1 style routing lookup as crm_auth: routing columns only (plan §4.4).
func (q *Queries) LookupUserByEmail(ctx context.Context, email string) (LookupUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, lookupUserByEmail, email)
	var i LookupUserByEmailRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}
