// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcspike

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const getSpikeItem = `-- name: GetSpikeItem :one
SELECT id, tenant_id, email, ip, parent_id, created_at
FROM app.spike_items
WHERE tenant_id = $1 AND id = $2
`

type GetSpikeItemParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetSpikeItemRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	Ip        *netip.Addr
	ParentID  uuid.NullUUID
	CreatedAt time.Time
}

func (q *Queries) GetSpikeItem(ctx context.Context, arg GetSpikeItemParams) (GetSpikeItemRow, error) {
	row := q.db.QueryRow(ctx, getSpikeItem, arg.TenantID, arg.ID)
	var i GetSpikeItemRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Ip,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const insertSpikeItem = `-- name: InsertSpikeItem :one
INSERT INTO app.spike_items (tenant_id, email, secret_hash, ip, parent_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, email, ip, parent_id, created_at
`

type InsertSpikeItemParams struct {
	TenantID   uuid.UUID
	Email      string
	SecretHash []byte
	Ip         *netip.Addr
	ParentID   uuid.NullUUID
	CreatedAt  time.Time
}

type InsertSpikeItemRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	Ip        *netip.Addr
	ParentID  uuid.NullUUID
	CreatedAt time.Time
}

func (q *Queries) InsertSpikeItem(ctx context.Context, arg InsertSpikeItemParams) (InsertSpikeItemRow, error) {
	row := q.db.QueryRow(ctx, insertSpikeItem,
		arg.TenantID,
		arg.Email,
		arg.SecretHash,
		arg.Ip,
		arg.ParentID,
		arg.CreatedAt,
	)
	var i InsertSpikeItemRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Ip,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const lookupSpikeItemByEmail = `-- name: LookupSpikeItemByEmail :one
SELECT id, tenant_id FROM app.spike_items WHERE email = $1
`

type LookupSpikeItemByEmailRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

// Phase 1 style lookup as crm_auth: routing columns only.
func (q *Queries) LookupSpikeItemByEmail(ctx context.Context, email string) (LookupSpikeItemByEmailRow, error) {
	row := q.db.QueryRow(ctx, lookupSpikeItemByEmail, email)
	var i LookupSpikeItemByEmailRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}
