// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMessage = `-- name: GetMessage :one
SELECT id, tenant_id, kind, template, recipient, payload, attempts
FROM app.outbox_messages
WHERE tenant_id = $1 AND id = $2 AND status = 'pending'
`

type GetMessageParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetMessageRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Kind      string
	Template  string
	Recipient string
	Payload   []byte
	Attempts  int32
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.TenantID, arg.ID)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Template,
		&i.Recipient,
		&i.Payload,
		&i.Attempts,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO app.outbox_messages (tenant_id, kind, template, recipient, payload, created_at, next_attempt_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMessageParams struct {
	TenantID      uuid.UUID
	Kind          string
	Template      string
	Recipient     string
	Payload       []byte
	CreatedAt     time.Time
	NextAttemptAt time.Time
}

// created_at and next_attempt_at are set explicitly by Enqueue (clock.Clock), not by the column
// defaults: deferDelay (ADR-024 §6) needs a created_at that matches the caller's clock in tests,
// and the two columns must agree with each other (M6).
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.TenantID,
		arg.Kind,
		arg.Template,
		arg.Recipient,
		arg.Payload,
		arg.CreatedAt,
		arg.NextAttemptAt,
	)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE app.outbox_messages
SET status = 'failed', payload = NULL, failed_at = $1, attempts = attempts + 1, last_error = $2
WHERE tenant_id = $3 AND id = $4 AND status = 'pending'
`

type MarkFailedParams struct {
	FailedAt  *time.Time
	LastError pgtype.Text
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed,
		arg.FailedAt,
		arg.LastError,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const markRecoverable = `-- name: MarkRecoverable :exec
UPDATE app.outbox_messages
SET attempts = attempts + 1, next_attempt_at = $1, last_error = $2
WHERE tenant_id = $3 AND id = $4 AND status = 'pending'
`

type MarkRecoverableParams struct {
	NextAttemptAt time.Time
	LastError     pgtype.Text
	TenantID      uuid.UUID
	ID            uuid.UUID
}

func (q *Queries) MarkRecoverable(ctx context.Context, arg MarkRecoverableParams) error {
	_, err := q.db.Exec(ctx, markRecoverable,
		arg.NextAttemptAt,
		arg.LastError,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const markSent = `-- name: MarkSent :exec
UPDATE app.outbox_messages
SET status = 'sent', payload = NULL, sent_at = $1, last_error = NULL
WHERE tenant_id = $2 AND id = $3 AND status = 'pending'
`

type MarkSentParams struct {
	SentAt   *time.Time
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkSent(ctx context.Context, arg MarkSentParams) error {
	_, err := q.db.Exec(ctx, markSent, arg.SentAt, arg.TenantID, arg.ID)
	return err
}
