// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deferMessage = `-- name: DeferMessage :execrows
UPDATE app.outbox_messages
SET next_attempt_at = $1
WHERE id = $2 AND status = 'pending' AND next_attempt_at = $3
`

type DeferMessageParams struct {
	NextAttemptAt         time.Time
	ID                    uuid.UUID
	ExpectedNextAttemptAt time.Time
}

// Isolates a per-message failure of the Dispatcher (AsTenant, GetMessage or the mark) from the
// rest of the batch (ADR-024 §6, INV-31): it moves only next_attempt_at, as crm_worker, with the
// UPDATE (next_attempt_at) privilege and the worker_lock policy that already exist for
// LockDueMessage (no new privilege). The condition on next_attempt_at is the optimistic check
// against another worker having already claimed and resolved the same message: 0 rows affected
// means that happened, and it is not an error. attempts and last_error are untouched: no delivery
// was attempted.
func (q *Queries) DeferMessage(ctx context.Context, arg DeferMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deferMessage, arg.NextAttemptAt, arg.ID, arg.ExpectedNextAttemptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTerminalMessages = `-- name: DeleteTerminalMessages :execrows
DELETE FROM app.outbox_messages
WHERE status <> 'pending' AND created_at < now() - interval '30 days'
`

func (q *Queries) DeleteTerminalMessages(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTerminalMessages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockDueMessage = `-- name: LockDueMessage :one
SELECT id, tenant_id, next_attempt_at, created_at FROM app.outbox_messages
WHERE status = 'pending' AND next_attempt_at <= $1
ORDER BY next_attempt_at, id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type LockDueMessageRow struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	NextAttemptAt time.Time
	CreatedAt     time.Time
}

// next_attempt_at and created_at are returned too: the Dispatcher needs them to defer the message
// (ADR-024 §6) without a second read, and crm_worker already has SELECT on both columns.
func (q *Queries) LockDueMessage(ctx context.Context, now time.Time) (LockDueMessageRow, error) {
	row := q.db.QueryRow(ctx, lockDueMessage, now)
	var i LockDueMessageRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NextAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}
