// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const lockDueMessage = `-- name: LockDueMessage :one
SELECT id, tenant_id FROM app.outbox_messages
WHERE status = 'pending' AND next_attempt_at <= $1
ORDER BY next_attempt_at, id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type LockDueMessageRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) LockDueMessage(ctx context.Context, now time.Time) (LockDueMessageRow, error) {
	row := q.db.QueryRow(ctx, lockDueMessage, now)
	var i LockDueMessageRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}
